class Theme:
    """Centralized color theme for the agent's UI components."""
    HEADER = "bold blue"
    GOAL = "italic"
    SUMMARY_TITLE = "bold cyan"
    SUMMARY_BORDER = "blue"
    STEP_PANEL_BORDER = "dim cyan"
    SUCCESS = "green"
    PROMPT = "cyan"
    ERROR = "bold red"