"""
Response models from AI service
"""
from dataclasses import dataclass, field
from typing import Dict, Any, Optional

@dataclass
class CodeResponse:
    """
    Response model for code generation.

    This class encapsulates the content generated by the AI service, along with metadata
    about the model used and the resources consumed.
    """
    content: str  # The generated code or text content.
    model: str  # The name of the AI model used to generate the response.
    usage: Dict[str, int] = field(default_factory=dict)  # Dictionary containing usage information (e.g., tokens used).
    metadata: Dict[str, Any] = field(default_factory=dict)  # Additional metadata about the response.